// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";


const MONGO_URI = process.env["MONGO_URI"];
if (!MONGO_URI) {
  throw new Error("MONGO_URI is not defined");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: MONGO_URI
  },
});
